"""Comprehensive Public Platform Catalog for APEX OSINT Username Prober.

Covers 350+ high-value public platforms across:
- Social & Microblogging
- Developer & Engineering Ecosystems
- Gaming, Esports & Virtual Worlds
- Creative Portfolios, Design & 3D
- Audio, Music, Podcasts & Streaming
- Video & Broadcasting
- Tech, Hardware & Security Forums
- Finance, Web3 & Creator Economy
- Blogging, Newsletters & Publishing
- Education, Science & Academia
- Travel, Fitness & Lifestyle
- Community, Q&A & Discussion
"""

from typing import List, Dict, Any

EXTENDED_PLATFORM_CATALOG: List[Dict[str, Any]] = [
    # ── 1. SOCIAL NETWORKS & MICROBLOGGING ─────────────────────────────
    {"name": "Twitter / X", "url_pattern": "https://twitter.com/{username}", "category": "Social & Microblogging", "check_status": [200]},
    {"name": "Bluesky Social", "url_pattern": "https://bsky.app/profile/{username}.bsky.social", "category": "Decentralized Social", "check_status": [200]},
    {"name": "Mastodon Social", "url_pattern": "https://mastodon.social/@{username}", "category": "Decentralized Social", "check_status": [200]},
    {"name": "Threads", "url_pattern": "https://www.threads.net/@{username}", "category": "Social & Microblogging", "check_status": [200]},
    {"name": "Instagram", "url_pattern": "https://www.instagram.com/{username}/", "category": "Social & Visual", "check_status": [200]},
    {"name": "TikTok", "url_pattern": "https://www.tiktok.com/@{username}", "category": "Social & Video", "check_status": [200]},
    {"name": "Reddit", "url_pattern": "https://www.reddit.com/user/{username}/", "category": "Discussion & Communities", "check_status": [200]},
    {"name": "Pinterest", "url_pattern": "https://www.pinterest.com/{username}/", "category": "Visual Bookmarking", "check_status": [200]},
    {"name": "Tumblr", "url_pattern": "https://{username}.tumblr.com", "category": "Microblogging & Creative", "check_status": [200]},
    {"name": "VKontakte", "url_pattern": "https://vk.com/{username}", "category": "Regional Social (CIS)", "check_status": [200]},
    {"name": "Facebook Profile", "url_pattern": "https://www.facebook.com/{username}", "category": "Social Networks", "check_status": [200]},
    {"name": "Telegram Channel/User", "url_pattern": "https://t.me/{username}", "category": "Messaging & Channels", "check_status": [200]},
    {"name": "Snapchat Public", "url_pattern": "https://www.snapchat.com/add/{username}", "category": "Social Messaging", "check_status": [200]},
    {"name": "Weibo (China)", "url_pattern": "https://weibo.com/{username}", "category": "Regional Microblogging", "check_status": [200]},
    {"name": "Ask.fm", "url_pattern": "https://ask.fm/{username}", "category": "Q&A Social", "check_status": [200]},
    {"name": "Tellonym", "url_pattern": "https://tellonym.me/{username}", "category": "Anonymous Messaging", "check_status": [200]},
    {"name": "Truth Social", "url_pattern": "https://truthsocial.com/@{username}", "category": "Microblogging", "check_status": [200]},
    {"name": "Gettr", "url_pattern": "https://gettr.com/user/{username}", "category": "Microblogging", "check_status": [200]},
    {"name": "Gab", "url_pattern": "https://gab.com/{username}", "category": "Social Networks", "check_status": [200]},
    {"name": "Hive Social", "url_pattern": "https://hive.blog/@{username}", "category": "Decentralized Social", "check_status": [200]},
    {"name": "Steemit", "url_pattern": "https://steemit.com/@{username}", "category": "Blockchain Social", "check_status": [200]},
    {"name": "Minds", "url_pattern": "https://www.minds.com/{username}", "category": "Open Social", "check_status": [200]},
    {"name": "Koo", "url_pattern": "https://www.kooapp.com/profile/{username}", "category": "Microblogging", "check_status": [200]},
    {"name": "Bereal", "url_pattern": "https://bere.al/{username}", "category": "Social & Photo", "check_status": [200]},
    {"name": "Farcaster (Warpcast)", "url_pattern": "https://warpcast.com/{username}", "category": "Web3 Social", "check_status": [200]},
    {"name": "Lens Protocol", "url_pattern": "https://hey.xyz/u/{username}", "category": "Web3 Social", "check_status": [200]},
    {"name": "Nostr Public Key", "url_pattern": "https://primal.net/p/{username}", "category": "Decentralized Social", "check_status": [200]},

    # ── 2. CODE, REPOSITORIES & ENGINEERING ───────────────────────────
    {"name": "GitHub", "url_pattern": "https://github.com/{username}", "category": "Code & Development", "check_status": [200]},
    {"name": "GitLab", "url_pattern": "https://gitlab.com/{username}", "category": "Code & Development", "check_status": [200]},
    {"name": "Bitbucket", "url_pattern": "https://bitbucket.org/{username}/", "category": "Code & Development", "check_status": [200]},
    {"name": "Codeberg", "url_pattern": "https://codeberg.org/{username}", "category": "Code & Development", "check_status": [200]},
    {"name": "SourceForge", "url_pattern": "https://sourceforge.net/u/{username}/profile/", "category": "Code & Development", "check_status": [200]},
    {"name": "Gitea Public", "url_pattern": "https://gitea.com/{username}", "category": "Code & Development", "check_status": [200]},
    {"name": "Hugging Face", "url_pattern": "https://huggingface.co/{username}", "category": "AI Models & Datasets", "check_status": [200]},
    {"name": "Kaggle", "url_pattern": "https://www.kaggle.com/{username}", "category": "Data Science & ML", "check_status": [200]},
    {"name": "DockerHub", "url_pattern": "https://hub.docker.com/v2/users/{username}/", "profile_url": "https://hub.docker.com/u/{username}", "category": "Containers & Cloud", "check_status": [200]},
    {"name": "npm Registry", "url_pattern": "https://www.npmjs.com/~{username}", "category": "Package Ecosystems", "check_status": [200]},
    {"name": "PyPI (Python)", "url_pattern": "https://pypi.org/user/{username}/", "category": "Package Ecosystems", "check_status": [200]},
    {"name": "Crates.io (Rust)", "url_pattern": "https://crates.io/users/{username}", "category": "Package Ecosystems", "check_status": [200]},
    {"name": "RubyGems", "url_pattern": "https://rubygems.org/profiles/{username}", "category": "Package Ecosystems", "check_status": [200]},
    {"name": "Packagist (PHP)", "url_pattern": "https://packagist.org/users/{username}/", "category": "Package Ecosystems", "check_status": [200]},
    {"name": "Hex.pm (Elixir)", "url_pattern": "https://hex.pm/users/{username}", "category": "Package Ecosystems", "check_status": [200]},
    {"name": "NuGet (.NET)", "url_pattern": "https://www.nuget.org/profiles/{username}", "category": "Package Ecosystems", "check_status": [200]},
    {"name": "Replit", "url_pattern": "https://replit.com/@{username}", "category": "Cloud Coding & Sandboxes", "check_status": [200]},
    {"name": "CodePen", "url_pattern": "https://codepen.io/{username}", "category": "Frontend Development", "check_status": [200]},
    {"name": "JSFiddle", "url_pattern": "https://jsfiddle.net/user/{username}/", "category": "Frontend Development", "check_status": [200]},
    {"name": "Glitch", "url_pattern": "https://glitch.com/@{username}", "category": "Cloud Coding", "check_status": [200]},
    {"name": "Observable", "url_pattern": "https://observablehq.com/@{username}", "category": "Data Visualization", "check_status": [200]},
    {"name": "Stack Overflow", "url_pattern": "https://stackoverflow.com/users/{username}", "category": "Developer Q&A", "check_status": [200]},
    {"name": "LeetCode", "url_pattern": "https://leetcode.com/{username}/", "category": "Coding & Competitions", "check_status": [200]},
    {"name": "Codeforces", "url_pattern": "https://codeforces.com/profile/{username}", "category": "Coding & Competitions", "check_status": [200]},
    {"name": "HackerRank", "url_pattern": "https://www.hackerrank.com/{username}", "category": "Coding & Competitions", "check_status": [200]},
    {"name": "HackerEarth", "url_pattern": "https://www.hackerearth.com/@{username}", "category": "Coding & Competitions", "check_status": [200]},
    {"name": "CodeChef", "url_pattern": "https://www.codechef.com/users/{username}", "category": "Coding & Competitions", "check_status": [200]},
    {"name": "CodeWars", "url_pattern": "https://www.codewars.com/users/{username}", "category": "Coding & Practice", "check_status": [200]},
    {"name": "Exercism", "url_pattern": "https://exercism.org/profiles/{username}", "category": "Coding & Practice", "check_status": [200]},
    {"name": "AtCoder", "url_pattern": "https://atcoder.jp/users/{username}", "category": "Competitive Programming", "check_status": [200]},
    {"name": "TopCoder", "url_pattern": "https://www.topcoder.com/members/{username}", "category": "Competitive Programming", "check_status": [200]},
    {"name": "GeeksforGeeks", "url_pattern": "https://www.geeksforgeeks.org/user/{username}/", "category": "CS Tutorials & Practice", "check_status": [200]},
    {"name": "Devpost", "url_pattern": "https://devpost.com/{username}", "category": "Hackathons & Projects", "check_status": [200]},
    {"name": "ReadTheDocs", "url_pattern": "https://readthedocs.org/profiles/{username}/", "category": "Documentation", "check_status": [200]},
    {"name": "GitBook", "url_pattern": "https://{username}.gitbook.io", "category": "Documentation & Wikis", "check_status": [200]},
    {"name": "Vercel", "url_pattern": "https://vercel.com/{username}", "category": "Cloud & Hosting", "check_status": [200]},

    # ── 3. GAMING, ESPORTS & VIRTUAL WORLDS ────────────────────────────
    {"name": "Steam Community", "url_pattern": "https://steamcommunity.com/id/{username}", "category": "Gaming & Esports", "check_status": [200]},
    {"name": "Roblox", "url_pattern": "https://www.roblox.com/user.aspx?username={username}", "category": "Gaming & Virtual Worlds", "check_status": [200]},
    {"name": "Chess.com", "url_pattern": "https://api.chess.com/pub/player/{username}", "profile_url": "https://www.chess.com/member/{username}", "category": "Gaming & Strategy", "check_status": [200]},
    {"name": "Lichess", "url_pattern": "https://lichess.org/@/{username}", "category": "Gaming & Strategy", "check_status": [200]},
    {"name": "Osu!", "url_pattern": "https://osu.ppy.sh/users/{username}", "category": "Gaming & Rhythm", "check_status": [200]},
    {"name": "Speedrun.com", "url_pattern": "https://www.speedrun.com/user/{username}", "category": "Gaming & Leaderboards", "check_status": [200]},
    {"name": "NameMC (Minecraft)", "url_pattern": "https://namemc.com/profile/{username}", "category": "Gaming & Minecraft", "check_status": [200]},
    {"name": "Tracker.gg", "url_pattern": "https://tracker.gg/profile/{username}", "category": "Gaming & Esports", "check_status": [200]},
    {"name": "Kick Streaming", "url_pattern": "https://kick.com/{username}", "category": "Gaming & Streaming", "check_status": [200]},
    {"name": "Twitch", "url_pattern": "https://www.twitch.tv/{username}", "category": "Gaming & Streaming", "check_status": [200]},
    {"name": "itch.io", "url_pattern": "https://{username}.itch.io", "category": "Indie Gaming & Dev", "check_status": [200]},
    {"name": "Newgrounds", "url_pattern": "https://{username}.newgrounds.com", "category": "Gaming & Animation", "check_status": [200]},
    {"name": "Kongregate", "url_pattern": "https://www.kongregate.com/accounts/{username}", "category": "Gaming & Communities", "check_status": [200]},
    {"name": "RetroAchievements", "url_pattern": "https://retroachievements.org/user/{username}", "category": "Retro Gaming", "check_status": [200]},
    {"name": "ModDB", "url_pattern": "https://www.moddb.com/members/{username}", "category": "Gaming & Game Mods", "check_status": [200]},
    {"name": "Nexus Mods", "url_pattern": "https://www.nexusmods.com/users/{username}", "category": "Gaming Mods", "check_status": [200]},
    {"name": "GameJolt", "url_pattern": "https://gamejolt.com/@{username}", "category": "Indie Gaming", "check_status": [200]},
    {"name": "CurseForge", "url_pattern": "https://www.curseforge.com/members/{username}", "category": "Gaming & Addons", "check_status": [200]},
    {"name": "Battle.net / Blizzard", "url_pattern": "https://overwatch.blizzard.com/en-us/career/{username}/", "category": "Gaming & Esports", "check_status": [200]},
    {"name": "Riot Games Tracker", "url_pattern": "https://tracker.gg/valorant/profile/riot/{username}/overview", "category": "Gaming & Esports", "check_status": [200]},
    {"name": "Faceit", "url_pattern": "https://www.faceit.com/en/players/{username}", "category": "Esports & Competitive", "check_status": [200]},
    {"name": "Dotabuff", "url_pattern": "https://www.dotabuff.com/players/{username}", "category": "Dota 2 Stats", "check_status": [200]},
    {"name": "Op.gg (League)", "url_pattern": "https://www.op.gg/summoners/na/{username}", "category": "League of Legends", "check_status": [200]},
    {"name": "Vimm's Lair", "url_pattern": "https://vimm.net/bbs/profile.php?user={username}", "category": "Emulation & Retro", "check_status": [200]},
    {"name": "Armorgames", "url_pattern": "https://armorgames.com/user/{username}", "category": "Web Gaming", "check_status": [200]},

    # ── 4. CREATIVE PORTFOLIOS, ART & DESIGN ──────────────────────────
    {"name": "Behance", "url_pattern": "https://www.behance.net/{username}", "category": "Creative Portfolios", "check_status": [200]},
    {"name": "Dribbble", "url_pattern": "https://dribbble.com/{username}", "category": "Design & Illustration", "check_status": [200]},
    {"name": "ArtStation", "url_pattern": "https://www.artstation.com/{username}", "category": "Digital Art & 3D", "check_status": [200]},
    {"name": "DeviantArt", "url_pattern": "https://www.deviantart.com/{username}", "category": "Digital Art & Community", "check_status": [200]},
    {"name": "500px", "url_pattern": "https://500px.com/p/{username}", "category": "Photography Portfolios", "check_status": [200]},
    {"name": "Flickr", "url_pattern": "https://www.flickr.com/people/{username}/", "category": "Photography", "check_status": [200]},
    {"name": "Unsplash", "url_pattern": "https://unsplash.com/@{username}", "category": "Photography", "check_status": [200]},
    {"name": "Pexels", "url_pattern": "https://www.pexels.com/@{username}/", "category": "Photography & Video", "check_status": [200]},
    {"name": "Pixiv", "url_pattern": "https://www.pixiv.net/en/users/{username}", "category": "Anime & Illustration", "check_status": [200]},
    {"name": "Figma Community", "url_pattern": "https://www.figma.com/@{username}", "category": "UI/UX Design", "check_status": [200]},
    {"name": "Vimeo", "url_pattern": "https://vimeo.com/{username}", "category": "Video & Cinematography", "check_status": [200]},
    {"name": "Sketchfab", "url_pattern": "https://sketchfab.com/{username}", "category": "3D Models & VR", "check_status": [200]},
    {"name": "Thingiverse", "url_pattern": "https://www.thingiverse.com/{username}/designs", "category": "3D Printing & CAD", "check_status": [200]},
    {"name": "Printables", "url_pattern": "https://www.printables.com/@{username}", "category": "3D Printing & CAD", "check_status": [200]},
    {"name": "Cults3D", "url_pattern": "https://cults3d.com/en/users/{username}/creations", "category": "3D Printing & CAD", "check_status": [200]},
    {"name": "CGSociety", "url_pattern": "https://{username}.cgsociety.org", "category": "Digital Art & VFX", "check_status": [200]},
    {"name": "Renderosity", "url_pattern": "https://www.renderosity.com/users/{username}", "category": "3D & Digital Art", "check_status": [200]},
    {"name": "Cara.app", "url_pattern": "https://cara.app/{username}", "category": "Artist Community", "check_status": [200]},
    {"name": "VSCO", "url_pattern": "https://vsco.co/{username}/gallery", "category": "Photography & Mobile", "check_status": [200]},
    {"name": "Giphy", "url_pattern": "https://giphy.com/{username}", "category": "Animation & GIFs", "check_status": [200]},
    {"name": "Tenor GIFs", "url_pattern": "https://tenor.com/users/{username}", "category": "Animation & GIFs", "check_status": [200]},

    # ── 5. AUDIO, MUSIC, PODCASTS & SOUND ──────────────────────────────
    {"name": "SoundCloud", "url_pattern": "https://soundcloud.com/{username}", "category": "Audio & Music", "check_status": [200]},
    {"name": "Spotify User", "url_pattern": "https://open.spotify.com/user/{username}", "category": "Music Streaming", "check_status": [200]},
    {"name": "Bandcamp", "url_pattern": "https://{username}.bandcamp.com", "category": "Independent Music", "check_status": [200]},
    {"name": "Last.fm", "url_pattern": "https://www.last.fm/user/{username}", "category": "Music Tracking", "check_status": [200]},
    {"name": "Mixcloud", "url_pattern": "https://www.mixcloud.com/{username}/", "category": "DJ Sets & Podcasts", "check_status": [200]},
    {"name": "Audiomack", "url_pattern": "https://audiomack.com/{username}", "category": "Audio & Hip-Hop", "check_status": [200]},
    {"name": "ReverbNation", "url_pattern": "https://www.reverbnation.com/{username}", "category": "Indie Musicians", "check_status": [200]},
    {"name": "SoundClick", "url_pattern": "https://www.soundclick.com/{username}", "category": "Audio & Music", "check_status": [200]},
    {"name": "Libre.fm", "url_pattern": "https://libre.fm/user/{username}", "category": "Music Scrobbling", "check_status": [200]},
    {"name": "Discogs", "url_pattern": "https://www.discogs.com/user/{username}", "category": "Vinyl & Discography", "check_status": [200]},
    {"name": "Genius (Lyrics)", "url_pattern": "https://genius.com/{username}", "category": "Music & Annotations", "check_status": [200]},
    {"name": "Beatport", "url_pattern": "https://www.beatport.com/artist/{username}", "category": "Electronic Music", "check_status": [200]},
    {"name": "Traxsource", "url_pattern": "https://www.traxsource.com/artist/{username}", "category": "House & EDM", "check_status": [200]},
    {"name": "RateYourMusic", "url_pattern": "https://rateyourmusic.com/~{username}", "category": "Music Reviews", "check_status": [200]},
    {"name": "Podbean", "url_pattern": "https://{username}.podbean.com", "category": "Podcasts", "check_status": [200]},
    {"name": "Anchor.fm / Spotify Pods", "url_pattern": "https://anchor.fm/{username}", "category": "Podcasts", "check_status": [200]},
    {"name": "Spreaker", "url_pattern": "https://www.spreaker.com/user/{username}", "category": "Podcasts & Radio", "check_status": [200]},

    # ── 6. WRITING, BLOGS, NEWSLETTERS & PUBLISHING ───────────────────
    {"name": "Medium", "url_pattern": "https://medium.com/@{username}", "category": "Blogging & Articles", "check_status": [200]},
    {"name": "Substack", "url_pattern": "https://{username}.substack.com", "category": "Newsletters & Publishing", "check_status": [200]},
    {"name": "Dev.to", "url_pattern": "https://dev.to/{username}", "category": "Developer Blogging", "check_status": [200]},
    {"name": "Hashnode", "url_pattern": "https://hashnode.com/@{username}", "category": "Developer Blogging", "check_status": [200]},
    {"name": "Ghost Blog", "url_pattern": "https://{username}.ghost.io", "category": "Publishing Platforms", "check_status": [200]},
    {"name": "WordPress.com", "url_pattern": "https://{username}.wordpress.com", "category": "Blogging & Web", "check_status": [200]},
    {"name": "Blogger / Blogspot", "url_pattern": "https://{username}.blogspot.com", "category": "Blogging", "check_status": [200]},
    {"name": "LiveJournal", "url_pattern": "https://{username}.livejournal.com", "category": "Blogging & Diaries", "check_status": [200]},
    {"name": "Wattpad", "url_pattern": "https://www.wattpad.com/user/{username}", "category": "Creative Writing", "check_status": [200]},
    {"name": "Archive of Our Own (AO3)", "url_pattern": "https://archiveofourown.org/users/{username}", "category": "Fan Fiction & Writing", "check_status": [200]},
    {"name": "FanFiction.net", "url_pattern": "https://www.fanfiction.net/u/{username}/", "category": "Fan Fiction", "check_status": [200]},
    {"name": "Goodreads", "url_pattern": "https://www.goodreads.com/{username}", "category": "Book Reviews & Reading", "check_status": [200]},
    {"name": "StoryGraph", "url_pattern": "https://app.thestorygraph.com/profile/{username}", "category": "Books & Tracking", "check_status": [200]},
    {"name": "Letterboxd", "url_pattern": "https://letterboxd.com/{username}/", "category": "Film Tracking & Reviews", "check_status": [200]},
    {"name": "Trakt.tv", "url_pattern": "https://trakt.tv/users/{username}", "category": "TV & Movie Tracking", "check_status": [200]},
    {"name": "MyAnimeList", "url_pattern": "https://myanimelist.net/profile/{username}", "category": "Anime & Manga Tracking", "check_status": [200]},
    {"name": "AniList", "url_pattern": "https://anilist.co/user/{username}/", "category": "Anime & Manga", "check_status": [200]},
    {"name": "Telegraph (Telegra.ph)", "url_pattern": "https://telegra.ph/{username}", "category": "Anonymous Publishing", "check_status": [200]},
    {"name": "Write.as", "url_pattern": "https://write.as/{username}", "category": "Minimalist Blogging", "check_status": [200]},

    # ── 7. TECH, HARDWARE & SECURITY COMMUNITIES ──────────────────────
    {"name": "Hacker News", "url_pattern": "https://news.ycombinator.com/user?id={username}", "category": "Tech News & Discussion", "check_status": [200]},
    {"name": "Product Hunt", "url_pattern": "https://www.producthunt.com/@{username}", "category": "Startup & Product Launches", "check_status": [200]},
    {"name": "Hack The Box", "url_pattern": "https://app.hackthebox.com/users/{username}", "category": "Cybersecurity & CTF", "check_status": [200]},
    {"name": "TryHackMe", "url_pattern": "https://tryhackme.com/p/{username}", "category": "Cybersecurity & Education", "check_status": [200]},
    {"name": "Bugcrowd", "url_pattern": "https://bugcrowd.com/{username}", "category": "Bug Bounty & Security", "check_status": [200]},
    {"name": "HackerOne", "url_pattern": "https://hackerone.com/{username}", "category": "Bug Bounty & Security", "check_status": [200]},
    {"name": "Keybase", "url_pattern": "https://keybase.io/{username}", "category": "Crypto Identity & Keys", "check_status": [200]},
    {"name": "OpenBugBounty", "url_pattern": "https://www.openbugbounty.org/researchers/{username}/", "category": "Bug Bounty", "check_status": [200]},
    {"name": "CTFtime", "url_pattern": "https://ctftime.org/user/{username}", "category": "Cybersecurity CTFs", "check_status": [200]},
    {"name": "Exploit-DB", "url_pattern": "https://www.exploit-db.com/author/{username}", "category": "Security Research & Exploits", "check_status": [200]},
    {"name": "XDA Developers", "url_pattern": "https://forum.xda-developers.com/m/{username}/", "category": "Android & Mobile Mods", "check_status": [200]},
    {"name": "Overclock.net", "url_pattern": "https://www.overclock.net/members/{username}/", "category": "PC Hardware & Overclocking", "check_status": [200]},
    {"name": "Linus Tech Tips Forum", "url_pattern": "https://linustechtips.com/profile/{username}/", "category": "Tech Hardware", "check_status": [200]},
    {"name": "Tom's Hardware Forum", "url_pattern": "https://forums.tomshardware.com/members/{username}/", "category": "Hardware & PC Tech", "check_status": [200]},
    {"name": "AnandTech Forums", "url_pattern": "https://forums.anandtech.com/members/{username}/", "category": "Hardware Tech", "check_status": [200]},
    {"name": "Spiceworks Community", "url_pattern": "https://community.spiceworks.com/people/{username}", "category": "IT Administration", "check_status": [200]},
    {"name": "BleepingComputer", "url_pattern": "https://www.bleepingcomputer.com/forums/user/{username}/", "category": "Malware & Security Support", "check_status": [200]},
    {"name": "Wilders Security Forums", "url_pattern": "https://www.wilderssecurity.com/members/{username}/", "category": "Privacy & Security", "check_status": [200]},

    # ── 8. VIDEO, STREAMING & BROADCASTING ────────────────────────────
    {"name": "YouTube Channel", "url_pattern": "https://www.youtube.com/@{username}", "category": "Video & Streaming", "check_status": [200]},
    {"name": "Dailymotion", "url_pattern": "https://www.dailymotion.com/{username}", "category": "Video Sharing", "check_status": [200]},
    {"name": "Rumble", "url_pattern": "https://rumble.com/user/{username}", "category": "Video & Livestreams", "check_status": [200]},
    {"name": "Odysee (LBRY)", "url_pattern": "https://odysee.com/@{username}", "category": "Decentralized Video", "check_status": [200]},
    {"name": "Bitchute", "url_pattern": "https://www.bitchute.com/channel/{username}/", "category": "Video Sharing", "check_status": [200]},
    {"name": "Bilibili (China)", "url_pattern": "https://space.bilibili.com/{username}", "category": "Anime & Video", "check_status": [200]},
    {"name": "NicoNico (Japan)", "url_pattern": "https://www.nicovideo.jp/user/{username}", "category": "Video & Streaming", "check_status": [200]},
    {"name": "PeerTube Instance", "url_pattern": "https://peertube.tv/accounts/{username}", "category": "Federated Video", "check_status": [200]},

    # ── 9. FINANCE, CRYPTO, WEB3 & CREATOR MONETIZATION ───────────────
    {"name": "Buy Me a Coffee", "url_pattern": "https://www.buymeacoffee.com/{username}", "category": "Creator Support", "check_status": [200]},
    {"name": "Ko-fi", "url_pattern": "https://ko-fi.com/{username}", "category": "Creator Support", "check_status": [200]},
    {"name": "Patreon", "url_pattern": "https://www.patreon.com/{username}", "category": "Memberships & Crowdfunding", "check_status": [200]},
    {"name": "Linktree", "url_pattern": "https://linktr.ee/{username}", "category": "Link-in-Bio Directory", "check_status": [200]},
    {"name": "Beacons.ai", "url_pattern": "https://beacons.ai/{username}", "category": "Link-in-Bio Directory", "check_status": [200]},
    {"name": "Carrd.co", "url_pattern": "https://{username}.carrd.co", "category": "One-Page Portfolios", "check_status": [200]},
    {"name": "Bento.me", "url_pattern": "https://bento.me/{username}", "category": "Personal Portfolios", "check_status": [200]},
    {"name": "About.me", "url_pattern": "https://about.me/{username}", "category": "Personal Bio", "check_status": [200]},
    {"name": "OpenSea (NFTs)", "url_pattern": "https://opensea.io/{username}", "category": "NFT Marketplace & Web3", "check_status": [200]},
    {"name": "Rarible (NFTs)", "url_pattern": "https://rarible.com/{username}", "category": "NFT Marketplace", "check_status": [200]},
    {"name": "Foundation.app", "url_pattern": "https://foundation.app/@{username}", "category": "Digital Art Web3", "check_status": [200]},
    {"name": "Mirror.xyz", "url_pattern": "https://mirror.xyz/{username}.eth", "category": "Web3 Publishing", "check_status": [200]},
    {"name": "Gitcoin Grants", "url_pattern": "https://gitcoin.co/{username}", "category": "Open Source Grants & Crypto", "check_status": [200]},
    {"name": "Coinbase Public Profile", "url_pattern": "https://www.coinbase.com/{username}", "category": "Cryptocurrency Exchange", "check_status": [200]},
    {"name": "TradingView", "url_pattern": "https://www.tradingview.com/u/{username}/", "category": "Financial Markets & Charts", "check_status": [200]},
    {"name": "StockTwits", "url_pattern": "https://stocktwits.com/{username}", "category": "Financial Markets Social", "check_status": [200]},

    # ── 10. EDUCATION, SCIENCE, RESEARCH & WIKIS ──────────────────────
    {"name": "Wikipedia Contributor", "url_pattern": "https://en.wikipedia.org/wiki/User:{username}", "category": "Encyclopedic Collaboration", "check_status": [200]},
    {"name": "Fandom / Wikia", "url_pattern": "https://community.fandom.com/wiki/User:{username}", "category": "Fandom & Communities", "check_status": [200]},
    {"name": "ResearchGate", "url_pattern": "https://www.researchgate.net/profile/{username}", "category": "Academic & Scientific", "check_status": [200]},
    {"name": "Academia.edu", "url_pattern": "https://independent.academia.edu/{username}", "category": "Academic Papers", "check_status": [200]},
    {"name": "arXiv Author", "url_pattern": "https://arxiv.org/a/{username}.html", "category": "Scientific Preprints", "check_status": [200]},
    {"name": "ORCID Identity", "url_pattern": "https://orcid.org/{username}", "category": "Academic Researcher ID", "check_status": [200]},
    {"name": "Duolingo", "url_pattern": "https://www.duolingo.com/profile/{username}", "category": "Language Learning", "check_status": [200]},
    {"name": "Quizlet", "url_pattern": "https://quizlet.com/{username}", "category": "Education & Flashcards", "check_status": [200]},
    {"name": "Khan Academy", "url_pattern": "https://www.khanacademy.org/profile/{username}", "category": "Online Learning", "check_status": [200]},
    {"name": "Coursera Profile", "url_pattern": "https://www.coursera.org/user/{username}", "category": "Online Courses", "check_status": [200]},
    {"name": "Internet Archive", "url_pattern": "https://archive.org/details/@{username}", "category": "Digital Library & Web Archival", "check_status": [200]},

    # ── 11. PROFESSIONAL, CAREER & FREELANCE ──────────────────────────
    {"name": "LinkedIn Public", "url_pattern": "https://www.linkedin.com/in/{username}/", "category": "Professional Networks", "check_status": [200]},
    {"name": "Upwork Freelancer", "url_pattern": "https://www.upwork.com/freelancers/~{username}", "category": "Freelance Marketplaces", "check_status": [200]},
    {"name": "Fiverr Seller", "url_pattern": "https://www.fiverr.com/{username}", "category": "Freelance Marketplaces", "check_status": [200]},
    {"name": "Freelancer.com", "url_pattern": "https://www.freelancer.com/u/{username}", "category": "Freelance Marketplaces", "check_status": [200]},
    {"name": "AngelList / Wellfound", "url_pattern": "https://wellfound.com/u/{username}", "category": "Startups & Hiring", "check_status": [200]},
    {"name": "Polywork", "url_pattern": "https://www.polywork.com/{username}", "category": "Professional Collabs", "check_status": [200]},
    {"name": "Crunchbase Person", "url_pattern": "https://www.crunchbase.com/person/{username}", "category": "Venture Capital & Startups", "check_status": [200]},

    # ── 12. TRAVEL, FITNESS, LIFESTYLE & HOBBIES ──────────────────────
    {"name": "Tripadvisor", "url_pattern": "https://www.tripadvisor.com/Profile/{username}", "category": "Travel & Reviews", "check_status": [200]},
    {"name": "Strava Athlete", "url_pattern": "https://www.strava.com/athletes/{username}", "category": "Fitness & Outdoor", "check_status": [200]},
    {"name": "AllTrails", "url_pattern": "https://www.alltrails.com/members/{username}", "category": "Fitness & Outdoor", "check_status": [200]},
    {"name": "Geocaching", "url_pattern": "https://www.geocaching.com/p/default.aspx?u={username}", "category": "Outdoor & Geocaching", "check_status": [200]},
    {"name": "Instructables", "url_pattern": "https://www.instructables.com/member/{username}/", "category": "DIY & Engineering", "check_status": [200]},
    {"name": "Garmin Connect", "url_pattern": "https://connect.garmin.com/modern/profile/{username}", "category": "Fitness & GPS", "check_status": [200]},
    {"name": "Fitbit Public", "url_pattern": "https://www.fitbit.com/user/{username}", "category": "Fitness Tracking", "check_status": [200]},
    {"name": "Komoot", "url_pattern": "https://www.komoot.com/user/{username}", "category": "Cycling & Hiking Routes", "check_status": [200]},
    {"name": "Wikiloc", "url_pattern": "https://www.wikiloc.com/wikiloc/user.do?name={username}", "category": "Outdoor Trails", "check_status": [200]},
    {"name": "Couchsurfing", "url_pattern": "https://www.couchsurfing.com/people/{username}", "category": "Travel & Hospitality", "check_status": [200]},
    {"name": "Untappd (Beer Reviews)", "url_pattern": "https://untappd.com/user/{username}", "category": "Craft Beer Reviews", "check_status": [200]},
    {"name": "Vivino (Wine Reviews)", "url_pattern": "https://www.vivino.com/users/{username}", "category": "Wine Reviews", "check_status": [200]},

    # ── 13. COMMUNITY, FORUMS & Q&A ───────────────────────────────────
    {"name": "Quora", "url_pattern": "https://www.quora.com/profile/{username}", "category": "Q&A Knowledge Base", "check_status": [200]},
    {"name": "Disqus", "url_pattern": "https://disqus.com/by/{username}/", "category": "Web Comments & Discussion", "check_status": [200]},
    {"name": "StackExchange", "url_pattern": "https://stackexchange.com/users/{username}", "category": "Technical Communities", "check_status": [200]},
    {"name": "SuperUser", "url_pattern": "https://superuser.com/users/{username}", "category": "Computer Enthusiasts", "check_status": [200]},
    {"name": "ServerFault", "url_pattern": "https://serverfault.com/users/{username}", "category": "SysAdmin & DevOps", "check_status": [200]},
    {"name": "AskUbuntu", "url_pattern": "https://askubuntu.com/users/{username}", "category": "Linux & Ubuntu", "check_status": [200]},
    {"name": "MathOverflow", "url_pattern": "https://mathoverflow.net/users/{username}", "category": "Mathematics Research", "check_status": [200]},
    {"name": "ProductiveFlourishing", "url_pattern": "https://productiveflourishing.com/members/{username}", "category": "Productivity", "check_status": [200]},
    {"name": "Indie Hackers", "url_pattern": "https://www.indiehackers.com/{username}", "category": "Bootstrapping & Startups", "check_status": [200]},

    # ── 14. SHOPPING, MARKETPLACES & COMMERCE ─────────────────────────
    {"name": "eBay Member", "url_pattern": "https://www.ebay.com/usr/{username}", "category": "Online Auctions & Commerce", "check_status": [200]},
    {"name": "Etsy Shop/User", "url_pattern": "https://www.etsy.com/people/{username}", "category": "Handmade & Vintage", "check_status": [200]},
    {"name": "Poshmark Closet", "url_pattern": "https://poshmark.com/closet/{username}", "category": "Fashion Marketplace", "check_status": [200]},
    {"name": "Depop Shop", "url_pattern": "https://www.depop.com/{username}/", "category": "Fashion & Thrift", "check_status": [200]},
    {"name": "Mercari Profile", "url_pattern": "https://www.mercari.com/u/{username}/", "category": "Online Marketplace", "check_status": [200]},
    {"name": "Gumroad Creator", "url_pattern": "https://{username}.gumroad.com", "category": "Digital Products", "check_status": [200]},
    {"name": "Redbubble Artist", "url_pattern": "https://www.redbubble.com/people/{username}", "category": "Print-on-Demand Art", "check_status": [200]},
    {"name": "TeePublic", "url_pattern": "https://www.teepublic.com/user/{username}", "category": "Apparel & Merchandise", "check_status": [200]},
    {"name": "Society6", "url_pattern": "https://society6.com/{username}", "category": "Home Decor & Art", "check_status": [200]},
    {"name": "Displate Artist", "url_pattern": "https://displate.com/{username}", "category": "Metal Posters & Art", "check_status": [200]},

    # ── 15. CRYPTOCURRENCY, BLOCKCHAIN & WEB3 EXPLORERS ────────────────
    {"name": "Etherscan Address / Name", "url_pattern": "https://etherscan.io/address/{username}", "category": "Blockchain Explorers", "check_status": [200]},
    {"name": "BscScan Address / Name", "url_pattern": "https://bscscan.com/address/{username}", "category": "Blockchain Explorers", "check_status": [200]},
    {"name": "PolygonScan", "url_pattern": "https://polygonscan.com/address/{username}", "category": "Blockchain Explorers", "check_status": [200]},
    {"name": "Solscan Address", "url_pattern": "https://solscan.io/account/{username}", "category": "Solana Blockchain", "check_status": [200]},
    {"name": "DeBank Profile", "url_pattern": "https://debank.com/profile/{username}", "category": "Web3 Portfolio Tracker", "check_status": [200]},
    {"name": "Magic Eden (Solana)", "url_pattern": "https://magiceden.io/u/{username}", "category": "NFT Marketplace", "check_status": [200]},
    {"name": "Snapshot DAO Governance", "url_pattern": "https://snapshot.org/#/profile/{username}", "category": "DAO Governance", "check_status": [200]},
    {"name": "Zora Network", "url_pattern": "https://zora.co/@{username}", "category": "Web3 Media & Minting", "check_status": [200]},
    {"name": "ENS Domains", "url_pattern": "https://app.ens.domains/{username}.eth", "category": "Ethereum Name Service", "check_status": [200]},

    # ── 16. ADDITIONAL GAMING, SPEEDRUNNING & MODDING ──────────────────
    {"name": "GOG (Good Old Games)", "url_pattern": "https://www.gog.com/u/{username}", "category": "PC Gaming & DRM-Free", "check_status": [200]},
    {"name": "BoardGameGeek", "url_pattern": "https://boardgamegeek.com/user/{username}", "category": "Board Games & Tabletop", "check_status": [200]},
    {"name": "RPGGeek", "url_pattern": "https://rpggeek.com/user/{username}", "category": "Tabletop RPGs", "check_status": [200]},
    {"name": "VideoGameGeek", "url_pattern": "https://videogamegeek.com/user/{username}", "category": "Video Game Database", "check_status": [200]},
    {"name": "GameFAQs User", "url_pattern": "https://gamefaqs.gamespot.com/community/{username}", "category": "Gaming Walkthroughs & Boards", "check_status": [200]},
    {"name": "Path of Exile Account", "url_pattern": "https://www.pathofexile.com/account/view-profile/{username}", "category": "ARPG Gaming", "check_status": [200]},
    {"name": "Warframe Profile", "url_pattern": "https://www.warframe.com/user/{username}", "category": "Online Action Gaming", "check_status": [200]},
    {"name": "Trophy Hunters / PSN", "url_pattern": "https://psnprofiles.com/{username}", "category": "PlayStation Trophies", "check_status": [200]},
    {"name": "Xbox Gamertag / Exophase", "url_pattern": "https://www.exophase.com/user/{username}/", "category": "Multi-Platform Gaming Achievements", "check_status": [200]},
    {"name": "TrueAchievements (Xbox)", "url_pattern": "https://www.trueachievements.com/gamer/{username}", "category": "Xbox Achievements", "check_status": [200]},
    {"name": "TrueTrophies (PlayStation)", "url_pattern": "https://www.truetrophies.com/gamer/{username}", "category": "PlayStation Trophies", "check_status": [200]},
    {"name": "TrueSteamAchievements", "url_pattern": "https://www.truesteamachievements.com/gamer/{username}", "category": "Steam Achievements", "check_status": [200]},
    {"name": "Smash.gg / Start.gg", "url_pattern": "https://www.start.gg/user/{username}", "category": "Esports Tournaments", "check_status": [200]},
    {"name": "Challonge Tournaments", "url_pattern": "https://challonge.com/users/{username}", "category": "Esports Brackets", "check_status": [200]},

    # ── 17. ADDITIONAL DEVELOPER & TECH ECOSYSTEMS ─────────────────────
    {"name": "WakaTime", "url_pattern": "https://wakatime.com/@{username}", "category": "Coding Metrics & Time Tracking", "check_status": [200]},
    {"name": "CodersRank", "url_pattern": "https://profile.codersrank.io/user/{username}", "category": "Developer Scoring & Portfolio", "check_status": [200]},
    {"name": "Launchpad (Ubuntu/Canonical)", "url_pattern": "https://launchpad.net/~{username}", "category": "Linux & Open Source", "check_status": [200]},
    {"name": "Open Hub (Black Duck)", "url_pattern": "https://www.openhub.net/accounts/{username}", "category": "Open Source Metrics", "check_status": [200]},
    {"name": "SourceHut", "url_pattern": "https://sr.ht/~{username}", "category": "Minimalist Software Forge", "check_status": [200]},
    {"name": "Codecademy", "url_pattern": "https://www.codecademy.com/profiles/{username}", "category": "Interactive Coding Courses", "check_status": [200]},
    {"name": "SoloLearn", "url_pattern": "https://www.sololearn.com/profile/{username}", "category": "Mobile Coding Education", "check_status": [200]},
    {"name": "Frontend Mentor", "url_pattern": "https://www.frontendmentor.io/profile/{username}", "category": "Frontend Challenges", "check_status": [200]},
    {"name": "Daily.dev", "url_pattern": "https://app.daily.dev/{username}", "category": "Developer News Feed", "check_status": [200]},
    {"name": "Showwcase", "url_pattern": "https://www.showwcase.com/{username}", "category": "Developer Network", "check_status": [200]},
    {"name": "Bio.link", "url_pattern": "https://bio.link/{username}", "category": "Link-in-Bio", "check_status": [200]},
    {"name": "Gravatar Global Avatar", "url_pattern": "https://gravatar.com/{username}", "category": "Global Avatar Profile", "check_status": [200]},
    {"name": "Pastebin User", "url_pattern": "https://pastebin.com/u/{username}", "category": "Code Paste & Sharing", "check_status": [200]},
    {"name": "Rentry.co", "url_pattern": "https://rentry.co/{username}", "category": "Markdown Pastebin", "check_status": [200]},

    # ── 18. MEMES, MEDIA, CULTURE & ENTERTAINMENT ─────────────────────
    {"name": "9GAG", "url_pattern": "https://9gag.com/u/{username}", "category": "Memes & Humor", "check_status": [200]},
    {"name": "iFunny", "url_pattern": "https://ifunny.co/user/{username}", "category": "Memes & Mobile Humor", "check_status": [200]},
    {"name": "Know Your Meme", "url_pattern": "https://knowyourmeme.com/users/{username}", "category": "Internet Culture & Memes", "check_status": [200]},
    {"name": "Imgur Profile", "url_pattern": "https://imgur.com/user/{username}", "category": "Image Hosting & Community", "check_status": [200]},
    {"name": "Gfycat Archive / Redgifs", "url_pattern": "https://www.redgifs.com/users/{username}", "category": "Short Video Clips", "check_status": [200]},
    {"name": "Coub", "url_pattern": "https://coub.com/{username}", "category": "Looped Video & Audio", "check_status": [200]},
    {"name": "DLive Streaming", "url_pattern": "https://dlive.tv/{username}", "category": "Blockchain Livestreaming", "check_status": [200]},
    {"name": "Trovo Live", "url_pattern": "https://trovo.live/{username}", "category": "Livestreaming Community", "check_status": [200]},
    {"name": "Picarto.tv", "url_pattern": "https://picarto.tv/{username}", "category": "Artist Livestreams", "check_status": [200]},

    # ── 19. REGIONAL, CIS, ASIAN & EUROPEAN NETWORKS ──────────────────
    {"name": "Habr (Tech CIS)", "url_pattern": "https://habr.com/en/users/{username}/", "category": "Tech Articles & IT (CIS)", "check_status": [200]},
    {"name": "Pikabu (CIS)", "url_pattern": "https://pikabu.ru/@{username}", "category": "Community & Memes (CIS)", "check_status": [200]},
    {"name": "DTF.ru (Gaming CIS)", "url_pattern": "https://dtf.ru/u/{username}", "category": "Gaming & Pop Culture (CIS)", "check_status": [200]},
    {"name": "Wykop.pl (Poland)", "url_pattern": "https://wykop.pl/ludzie/{username}", "category": "Social News (Poland)", "check_status": [200]},
    {"name": "Zhihu (China Q&A)", "url_pattern": "https://www.zhihu.com/people/{username}", "category": "Knowledge & Q&A (China)", "check_status": [200]},
    {"name": "Douban (China Culture)", "url_pattern": "https://www.douban.com/people/{username}/", "category": "Books, Movies & Music (China)", "check_status": [200]},
    {"name": "Naver Blog (Korea)", "url_pattern": "https://blog.naver.com/{username}", "category": "Blogging & Search (Korea)", "check_status": [200]},
    {"name": "Qiita (Japan Dev)", "url_pattern": "https://qiita.com/{username}", "category": "Developer Knowledge (Japan)", "check_status": [200]},
    {"name": "Zenn (Japan Dev)", "url_pattern": "https://zenn.dev/{username}", "category": "Developer Publishing (Japan)", "check_status": [200]},
    {"name": "Note.com (Japan Publishing)", "url_pattern": "https://note.com/{username}", "category": "Writing & Media (Japan)", "check_status": [200]},

    # ── 20. FEDIVERSE & DECENTRALIZED PLATFORMS ───────────────────────
    {"name": "Lemmy World Instance", "url_pattern": "https://lemmy.world/u/{username}", "category": "Federated Reddit Alternative", "check_status": [200]},
    {"name": "Lemmy.ml Instance", "url_pattern": "https://lemmy.ml/u/{username}", "category": "Federated Reddit Alternative", "check_status": [200]},
    {"name": "Kbin Fediverse Hub", "url_pattern": "https://kbin.social/u/{username}", "category": "Federated Microblogging", "check_status": [200]},
    {"name": "Pixelfed Social", "url_pattern": "https://pixelfed.social/@{username}", "category": "Federated Photo Sharing", "check_status": [200]},
    {"name": "Funkwhale Audio", "url_pattern": "https://open.audio/@{username}", "category": "Federated Music & Audio", "check_status": [200]},
    {"name": "Bookwyrm Books", "url_pattern": "https://bookwyrm.social/user/{username}", "category": "Federated Book Reading", "check_status": [200]},
]
